### ISSUE TITLE
Fail to compile with assemblyscript >0.22

### ISSUE THREAD

**Issue by ffortier** [piotr-oles/as-proto#32]
It compiles fine with assemblyscript <=0.22, but fails with 0.23 and 0.24

```
ERROR TS2564: Property '~lib/as-proto/assembly/internal/FixedWriter/FixedWriter#buf' has no initializer and is not assigned in the constructor before 'this' is used or returned.
    :
 24 │ private buf: Uint8Array;
    │         ~~~
    └─ in ~lib/as-proto/assembly/internal/FixedWriter.ts(24,11)
    :
 34 │ this.buf = new Uint8Array(this.sizer.len);
    │                           ~~~~~~~~~~
    └─ in ~lib/as-proto/assembly/internal/FixedWriter.ts(34,31)
 ```
