### PR TITLE
fix code to compile with assemblyscript >= 0.23.

### LINKED ISSUE #32: Fail to compile with assemblyscript >0.22
It compiles fine with assemblyscript <=0.22, but fails with 0.23 and 0.24

```
ERROR TS2564: Property '~lib/as-proto/assembly/internal/FixedWriter/FixedWriter#buf' has no initializer and is not assigned in the constructor before 'this' is used or returned.
    :
 24 │ private buf: Uint8Array;
    │         ~~~
    └─ in ~lib/as-proto/assembly/internal/FixedWriter.ts(24,11)
    :
 34 │ this.buf = new Uint8Array(this.sizer.len);
    │                           ~~~~~~~~~~
    └─ in ~lib/as-proto/assembly/internal/FixedWriter.ts(34,31)
 ```

### PR DESCRIPTION
**Pull request by ffortier**
Fixes https://github.com/piotr-oles/as-proto/issues/32

AssemblyScript >=0.23 do not allow using `this` before all mandatory fields have been initialized. This cause the following error:

```
ERROR TS2564: Property '~lib/as-proto/assembly/internal/FixedWriter/FixedWriter#buf' has no initializer and is not assigned in the constructor before 'this' is used or returned.
    :
 24 │ private buf: Uint8Array;
    │         ~~~
    └─ in ~lib/as-proto/assembly/internal/FixedWriter.ts(24,11)
    :
 34 │ this.buf = new Uint8Array(this.sizer.len);
    │                           ~~~~~~~~~~
    └─ in ~lib/as-proto/assembly/internal/FixedWriter.ts(34,31)
```

To reproduce
```
npx yarn
cd packages/as-proto
npx asc assembly/index.ts
```

Changes:
1. Upgrade assemblyscript and @assemblyscript/loader to the latest version (0.24.1)
2. Add `const` variables to keep a ref on the `sizer`  and the `buf` so that we can reuse those in the constructor without using `this`.

### CODE REVIEW

**Review by piotr-oles — APPROVED** [review]
Looks good, thanks for these changes!
